language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
 - export REPO=`pwd`
install:
  - sudo apt-get update
  - sudo apt-get install -qq python-yaml python-dateutil
  - sudo apt-get install -qq python3-yaml python3-dateutil
  - sudo apt-get install -qq git mercurial bzr subversion
  - pip install -U setuptools tox tox-travis
  - echo $PYTHONPATH
  - python -c 'import sys;print(sys.path)'
  - python setup.py install
  - hg --version
  - bzr --version
  - git --version
  - svn --version
# command to run tests
script:
  - tox

notifications:
  email: false
after_success:
  - coveralls
